### ISSUE TITLE
Some dataset samples to run transformer

### ISSUE THREAD

**Issue by abzargar** [AmigoLab/SynthAnatomy#4]
Hi, where can I find your dataset samples for training_subjects and validation_subjects to run_transformer.py? Thank you.

**Comment by danieltudosiu** [comment]
Hi @abzargar,

Thank you for your interest in our work. 

If you are looking to reuse our weights we recommend datasets that are MRI T1w which could be found in open-source datasets such as  [OASIS](https://sites.wustl.edu/oasisbrains/).

Due to licensing and privacy concerns, we are not able to publicly share any datasets so we ask the users to obtain them themselves.

**Comment by abzargar** [comment]
@danieltudosiu Thank you for your quick reply. As you know, the training_subjects and validation_subjects should be paths to either a folder with .npy files or a CSV/TSV file with a 'path' column that stores full paths to .npy files. However, the raw Oasis dataset is not organized in the required format for this code. Do you have any preprocessing code or instructions to prepare the Oasis dataset for your run_transformer.py?

**Comment by danieltudosiu** [comment]
Hi @abzargar

In all honesty I do not have such code, I usually use find or ls to list all npy or nii.gz files and pipe the output into a file that has csv as file type termination and then nano it to add the path as the header.
